name: ML Pipeline

on: [push]

jobs:
  Session-5-MNIST-MLOPS-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Session-5/requirements.txt
        
    - name: Train model
      run: |
        python -u Session-5/train.py 2>&1 | grep -v "Training:"  # Filter out intermediate progress bars
        
    - name: Run tests
      run: |
        pytest  Session-5/test_model.py -v --capture=no

    - name: Debug file structure
      run: |
        pwd
        ls -la
        echo "Looking for model files:"
        find . -name "model_mnist_*.pth"
        echo "Looking for augmented samples:"
        find . -name "*.png"

    - name: Archive model and augmented samples
      uses: actions/upload-artifact@v4
      with:
        name: training-artifacts
        path: |
          ./model_mnist_*.pth
          ./augmented_samples/*.png
        retention-days: 90
        if-no-files-found: error