name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest tqdm torchsummary
        
    - name: Train model
      run: |
        python Session-5/train.py
        
    - name: Run tests
      run: |
        pytest Session-5/test_model.py -v

    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: Session-5/model_mnist_*.pth
        retention-days: 90
